using GameApi.Characters;
using Xunit;

namespace GameApi.Tests;

// Cross-language parity: the server's name-hash default (CharacterDefaults.FromName)
// must produce byte-for-byte the same character the client computes in
// game-client/src/sprites/config.js (configFromName). These vectors were generated by
// running that exact JS. If either side's hash drifts, this test fails — which is the
// point, because a mismatch would let a lobby tell the AI apart by its character.
public class CharacterHashTests
{
    // name -> expected FNV-1a hash (matches JS `hashName(name) >>> 0`).
    [Theory]
    [InlineData("player", 748274432u)]
    [InlineData("Jake", 2001227576u)]
    [InlineData("Emily", 2571828641u)]
    [InlineData("Marcus", 4217437228u)]
    [InlineData("Kyle", 580341998u)]
    [InlineData("aiBot42", 3318131718u)]
    public void HashName_MatchesJs(string name, uint expected)
    {
        Assert.Equal(expected, CharacterDefaults.HashName(name));
    }

    // name -> {base, hair, outfit, accessory} from the JS configFromName.
    [Theory]
    [InlineData("player", 14, 4, 10, 3)]
    [InlineData("Jake", 14, 7, 4, 0)]
    [InlineData("Emily", 17, 0, 18, 0)]
    [InlineData("Marcus", 4, 13, 5, 5)]
    [InlineData("Priya", 14, 15, 3, 4)]
    [InlineData("Zoe", 9, 11, 5, 3)]
    [InlineData("Kyle", 2, 9, 14, 3)]
    [InlineData("aiBot42", 0, 4, 6, 3)]
    [InlineData("Grace", 7, 1, 16, 2)]
    public void FromName_MatchesJs(string name, int b, int hair, int outfit, int accessory)
    {
        var cfg = CharacterDefaults.FromName(name);
        Assert.Equal(b, cfg.Base);
        Assert.Equal(hair, cfg.Hair);
        Assert.Equal(outfit, cfg.Outfit);
        Assert.Equal(accessory, cfg.Accessory);
    }

    // Tyler's hash lands acc==6 in the JS, which maps to "no accessory" (null) on both sides.
    [Fact]
    public void FromName_NoAccessoryCase_IsNull()
    {
        var cfg = CharacterDefaults.FromName("Tyler");
        Assert.Equal(7, cfg.Base);
        Assert.Equal(14, cfg.Hair);
        Assert.Equal(1, cfg.Outfit);
        Assert.Null(cfg.Accessory);
    }

    // Empty/null names fall back to "player" exactly like `name || "player"` in JS.
    [Fact]
    public void FromName_EmptyName_MatchesPlayer()
    {
        var fromEmpty = CharacterDefaults.FromName("");
        var fromNull = CharacterDefaults.FromName(null);
        var player = CharacterDefaults.FromName("player");
        Assert.Equal(player, fromEmpty);
        Assert.Equal(player, fromNull);
    }
}
